# Generated by Django 2.1.10 on 2019-11-27 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redcap_import', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='redcapconnection',
            name='primary_key_field',
        ),
        migrations.AddField(
            model_name='projectmetadata',
            name='primary_key_field',
            field=models.CharField(default='record_id', help_text='ex. record_id, study_id, etc.', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectmetadata',
            name='has_multiple_arms',
            field=models.BooleanField(default=False),
        ),
    ]
