# Generated by Django 2.1.10 on 2019-11-27 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redcap_import', '0002_auto_20191127_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armmetadata',
            name='arm_number',
            field=models.IntegerField(),
        ),
    ]
