# Generated by Django 3.2.9 on 2021-11-29 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redcap_importer', '0006_auto_20210922_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='redcapconnection',
            name='api_token',
        ),
        migrations.RemoveField(
            model_name='redcapconnection',
            name='name',
        ),
        migrations.AlterField(
            model_name='redcapconnection',
            name='unique_name',
            field=models.SlugField(help_text='A unique reference for this connection and associated Django app', unique=True),
        ),
    ]
