# Generated by Django 3.2.9 on 2021-11-29 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redcap_importer', '0007_auto_20211129_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmetadata',
            name='date_last_downloaded_data_mongo',
        ),
    ]
