# Generated by Django 3.2.3 on 2021-09-22 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redcap_importer', '0005_etllog'),
    ]

    operations = [
        migrations.AddField(
            model_name='etllog',
            name='user',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='etllog',
            name='status',
            field=models.CharField(choices=[('ETL started', 'ETL started'), ('ETL completed', 'ETL completed'), ('upload started', 'upload started'), ('upload failed', 'upload failed'), ('upload complete', 'upload complete')], max_length=20),
        ),
    ]
