# Generated by Django 3.2.10 on 2023-11-06 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redcap_importer', '0010_auto_20230216_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='etllog',
            name='last_successful_record',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='etllog',
            name='last_successful_record_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
